- hosts: all
  become: true
  roles:
    - common

- hosts: router
  become: true
  roles:
    - router
    - dhcp

- hosts: web
  become: true
  roles:
    - web
    - clientes1

- hosts: cliente
  become: true
  roles:
    - clientes2
 
- hosts: clienteex
  become: true
  roles:
    - clientes3

- hosts: all
  become: true
  roles:
    - reboot
